server:
  port: 8080
  host: "0.0.0.0"
  context-path: "/api"

database:
  url: "jdbc:h2:mem:testdb"
  username: "sa"
  password: ""
  driver-class-name: "org.h2.Driver"

cache:
  enabled: true
  max-size: 1000
  expire-after-write-minutes: 30

metrics:
  enabled: true
  endpoint: "/metrics"

api:
  version: "v1"
  documentation:
    enabled: true
    path: "/swagger-ui"

# Environment-specific configurations can be added here
# Development profile
---
spring:
  profiles: development
server:
  port: 8081
database:
  url: "jdbc:h2:mem:devdb"

# Production profile  
---
spring:
  profiles: production
server:
  port: 8080
cache:
  max-size: 10000
  expire-after-write-minutes: 60
metrics:
  enabled: true
